### ISSUE TITLE
make define challenges not working

### ISSUE THREAD

**Issue by AmaurX** [duckietown/aido-robotarium-evaluation-form#8]
@AndreaCensi , when trying to run make define-challenges on your branch, I get the following error. I am supposed to do something else before ? (BTW what exactly is this command supposed to do?)
```make define-challenge 
dts challenges define --config aido2_LF_robotarium-testing.challenge.yaml
INFO:dts:duckietown-shell 4.0.13

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
INFO:duckietown-challenges:duckietown-challenges 4.0.12
INFO:dts:Detected duckietown-challenges 4.0.12 
Duckietown Shell commands version 4.0.9
DEBUG:dts:Checking docker environment for user amaury


dts :  message from server: Last blog post:
    :                     : 
    :                     :   Countdown to AI-DO 2!
    :                     : https://www.duckietown.org/archives/34686
INFO:dts:context: .
DEBUG:dts:Running docker build --pull -t docker.io/AmaurX/aido2-lf-real-testing-hw-evaluation-evaluator:2019_04_15_10_29_05 -f ./Dockerfile .
invalid argument "docker.io/AmaurX/aido2-lf-real-testing-hw-evaluation-evaluator:2019_04_15_10_29_05" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.

dts :  Traceback (most recent call last):
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 45, in cli_main
    :      cli_main_()
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 116, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/amaury/.dt-shell/commands/challenges/define/command.py", line 112, in command
    :      no_cache, registry_info=ri)
    :    File "/home/amaury/.dt-shell/commands/challenges/define/command.py", line 163, in build_image
    :      subprocess.check_call(cmd)
    :    File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    :      raise CalledProcessError(retcode, cmd)
    :  subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '-t', 'docker.io/AmaurX/aido2-lf-real-testing-hw-evaluation-evaluator:2019_04_15_10_29_05', '-f', './Dockerfile', '.']' returned non-zero exit status 125.

dts :  Please report that you are using:
    :  
    :  duckietown-shell-commands: 4.0.9
    :  python: "3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]"
    :  duckietown-shell: 4.0.13```

**Comment by AndreaCensi** [comment]
@AmaurX is your dockerhub username AmaurX with capitals?

**Comment by AndreaCensi** [comment]
@AmaurX looks like it isn't: https://hub.docker.com/u/amaurx

**Comment by AmaurX** [comment]
@AndreaCensi yes, dockerhub only takes lowwercase characters as username, so I didnt have a choice there

**Comment by AmaurX** [comment]
I guess it is because my duckietown name is AmaurX with capitals right?
